### ISSUE TITLE
bug:hunt-net echo not work

### ISSUE THREAD

**Issue by zhangyuchun** [huntlabs/hunt-net#2]

**Comment by Heromyth** [comment]
Fixed

**Comment by ibroheem** [comment]
Actually still not compiling, the echo example is outdated.

```
source/main.d(20,11): Error: no property `handler` for type `hunt.net.Connection.Connection`
source/main.d(32,42): Error: template instance `Result!Connection` template `Result` is not defined

```

From

```
...
client.connect(8080, "127.0.0.1", 0, (Result!Connection result) {
       if (result.failed()) {
           logDebug(result.cause().toString());
           return;
       }
....
```

**Comment by zoujiaqing** [comment]
@xiaoshuaisen look it :)

**Comment by ibroheem** [comment]
I've never got anything to run Hunt. I just have it lying there in dub packages.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

DUB version 1.18.0, built on Dec 14 2019

DMD64 D Compiler v2.089.1
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright

~/.dub/packages/hunt-net-0.4.6/hunt-net/examples/echo$ dub build --build=release --compiler=dmd
Performing "release" build using dmd for x86_64.
hunt 1.4.9: building configuration "library"...
hunt-net 0.4.6: building configuration "default"...
hunt-net-echo ~master: building configuration "application"...
source/app.d(27,13): Error: no property handler for type hunt.net.Connection.Connection
source/app.d(37,43): Error: template instance Result!Connection template Result is not defined
dmd failed with exit code 1.


```

**Comment by zoujiaqing** [comment]
@ibroheem fixed.
